# Generated by Django 6.0.7 on 2026-10-04 16:27

import django.db.models.deletion
import rooms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=rooms.models.generate_room_code, max_length=6, unique=True)),
                ('host_session_key', models.CharField(max_length=128)),
                ('game_type', models.CharField(choices=[('LUDO', 'Ludo'), ('CHESS_STANDARD', 'Standard Chess (2 Players)'), ('CHESS_4WAY', '4-Way Chess (4 Players)'), ('CHESS_BUGHOUSE', 'Bughouse / Double Chess (4 Players)')], default='LUDO', max_length=32)),
                ('variant', models.CharField(default='4P', max_length=32)),
                ('max_players', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('LOBBY', 'Lobby'), ('PLAYING', 'In Progress'), ('FINISHED', 'Finished')], default='LOBBY', max_length=16)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('turn_timer_sec', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6)),
                ('game_type', models.CharField(max_length=32)),
                ('variant', models.CharField(max_length=32)),
                ('winner_info', models.JSONField(default=dict)),
                ('players_summary', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128)),
                ('reconnect_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('player_name', models.CharField(max_length=64)),
                ('seat_index', models.IntegerField(default=0)),
                ('color', models.CharField(default='red', max_length=32)),
                ('is_host', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.gameroom')),
            ],
            options={
                'unique_together': {('room', 'seat_index')},
            },
        ),
    ]
