# Generated by Django 5.1.15 on 2026-09-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('tic_tac_toe', 'Tic-Tac-Toe'), ('rock_paper_scissors', 'Rock Paper Scissors'), ('connect_four', 'Connect Four')], default='tic_tac_toe', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='host_session_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_index=True, editable=False, help_text='Unique 6-character room code.', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'Game In Progress'), ('finished', 'Game Finished')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('session_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_host', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('slot_index', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_index'],
            },
        ),
        migrations.DeleteModel(
            name='RoomPlayer',
        ),
    ]
