# Generated by Django 6.0.7 on 2026-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='rules_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='game_type',
            field=models.CharField(choices=[('LUDO', 'Ludo'), ('CHESS_STANDARD', 'Standard Chess (2 Players)'), ('CHESS_4WAY', '4-Way Chess (4 Players)'), ('CHESS_BUGHOUSE', 'Bughouse / Double Chess (4 Players)'), ('CARD_UNO', 'Uno / Color Match'), ('CARD_POKER', "Texas Hold'em Poker"), ('CARD_BLACKJACK', 'Blackjack'), ('CARD_RUMMY', 'Rummy')], default='LUDO', max_length=32),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('LOBBY', 'Waiting in Lobby'), ('PLAYING', 'In Progress'), ('FINISHED', 'Finished')], default='LOBBY', max_length=16),
        ),
    ]
