# Generated by Django 5.1.15 on 2026-09-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_remove_room_game_id_remove_room_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='tic_tac_toe', max_length=50)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('final_state', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='rooms.room')),
            ],
            options={
                'ordering': ['-ended_at'],
            },
        ),
    ]
